version: '3.8'
services:
  db:
    image: postgres:13.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mrnobody
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://mrnobody:password@db:5432/dbname
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id

volumes:
  pgdata:
